; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "BillKro-Chillkro"
#define MyAppVersion "1.5"
#define MyAppPublisher "Ace One Tech"
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "MyProg-x64.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{EE5D2F2E-C05F-4B15-B49B-8E11123D12DD}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=D:\Flutter Projects\Billkaro Software\billkaro_windows\Installers
OutputBaseFilename=billkaro-chillkaro
SetupIconFile=D:\logo.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Program Files (x86)\Inno Setup 6\Examples\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\billkaro_windows.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\billkaro_windows.exp"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\billkaro_windows.lib"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\bitsdojo_window_windows_plugin.lib"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\camera_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\connectivity_plus_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\file_selector_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\flutter_blue_plus_winrt_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\flutter_bluetooth_classic_serial_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\flutter_thermal_printer_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\geolocator_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\pdfium.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\permission_handler_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\printing_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\share_plus_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\speech_to_text_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\sqlite3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\sqlite3_flutter_libs_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\universal_ble_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\url_launcher_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\webview_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\WebView2Loader.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Flutter Projects\Billkaro Software\billkaro_windows\build\windows\x64\runner\Release\data\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

