// // ignore_for_file: avoid_print
// import 'dart:io';

// import 'package:syncfusion_flutter_xlsio/xlsio.dart';

// void main() {
//   final rows = _findings();
//   final workbook = Workbook();
//   final sheet = workbook.worksheets[0];
//   sheet.name = 'QA Report';

//   const headers = [
//     'ID',
//     'Category',
//     'Severity',
//     'Module / Feature',
//     'Title',
//     'Description',
//     'Steps to Reproduce',
//     'Expected Behavior',
//     'Actual Behavior',
//     'Suggested Fix',
//     'File Path(s)',
//     'Status',
//     'Priority Rank',
//   ];

//   for (var c = 0; c < headers.length; c++) {
//     final cell = sheet.getRangeByIndex(1, c + 1);
//     cell.setText(headers[c]);
//     cell.cellStyle.bold = true;
//     cell.cellStyle.backColor = '#1F4E79';
//     cell.cellStyle.fontColor = '#FFFFFF';
//     cell.cellStyle.wrapText = true;
//   }

//   for (var r = 0; r < rows.length; r++) {
//     final row = rows[r];
//     for (var c = 0; c < row.length; c++) {
//       final cell = sheet.getRangeByIndex(r + 2, c + 1);
//       cell.setText(row[c]);
//       cell.cellStyle.wrapText = true;
//       if (c == 2) {
//         final sev = row[c];
//         if (sev == 'Critical') {
//           cell.cellStyle.backColor = '#FFC7CE';
//         } else if (sev == 'High') {
//           cell.cellStyle.backColor = '#FFE699';
//         } else if (sev == 'Medium') {
//           cell.cellStyle.backColor = '#FFF2CC';
//         }
//       }
//     }
//   }

//   sheet.getRangeByIndex(1, 1, rows.length + 1, headers.length).autoFitColumns();

//   _addSummarySheet(workbook, rows);

//   final outDir = Directory('QA_Reports');
//   if (!outDir.existsSync()) outDir.createSync(recursive: true);
//   final fileName =
//       'Billkaro_QA_Report_${DateTime.now().toIso8601String().split('T').first}.xlsx';
//   final outPath = '${outDir.path}${Platform.pathSeparator}$fileName';
//   final bytes = workbook.saveAsStream();
//   workbook.dispose();
//   File(outPath).writeAsBytesSync(bytes);
//   print('Report saved: $outPath');
// }

// void _addSummarySheet(Workbook workbook, List<List<String>> rows) {
//   final sheet = workbook.worksheets.addWithName('Summary');
//   sheet.getRangeByName('A1').setText('Billkaro Windows — QA Test Report');
//   sheet.getRangeByName('A1').cellStyle.bold = true;
//   sheet.getRangeByName('A1').cellStyle.fontSize = 16;

//   sheet.getRangeByName('A3').setText('Report Date');
//   sheet.getRangeByName('B3').setText(DateTime.now().toString().split('.').first);
//   sheet.getRangeByName('A4').setText('Project');
//   sheet.getRangeByName('B4').setText('billkaro_windows (Billkaro ChillKaro Desktop)');
//   sheet.getRangeByName('A5').setText('Platform Tested');
//   sheet.getRangeByName('B5').setText('Windows (Flutter 3.35.2 / Dart 3.9.0)');
//   sheet.getRangeByName('A6').setText('Build Status');
//   sheet.getRangeByName('B6').setText('PASS — Release build succeeded (392.8s)');
//   sheet.getRangeByName('A7').setText('Automated Tests');
//   sheet.getRangeByName('B7').setText(
//     'billkaro_windows: 0/1 pass (broken widget test). billkaro-app: 14/18 pass (4 compile failures — missing app_snackbar.dart).',
//   );
//   sheet.getRangeByName('A8').setText('Static Analysis');
//   sheet.getRangeByName('B8').setText('1441 issues (mostly info/warnings; 2 errors in test file)');
//   sheet.getRangeByName('A9').setText('Testing Method');
//   sheet.getRangeByName('B9').setText(
//     'Build verification, automated test run, static code analysis, and customer-journey code review (login → order → reports → KDS → printer → sync).',
//   );

//   final severityCounts = <String, int>{};
//   final categoryCounts = <String, int>{};
//   for (final row in rows) {
//     severityCounts[row[2]] = (severityCounts[row[2]] ?? 0) + 1;
//     categoryCounts[row[1]] = (categoryCounts[row[1]] ?? 0) + 1;
//   }

//   sheet.getRangeByName('A11').setText('Findings by Severity');
//   sheet.getRangeByName('A11').cellStyle.bold = true;
//   var r = 12;
//   for (final e in ['Critical', 'High', 'Medium', 'Low']) {
//     sheet.getRangeByIndex(r, 1).setText(e);
//     sheet.getRangeByIndex(r, 2).setNumber((severityCounts[e] ?? 0).toDouble());
//     r++;
//   }

//   r += 1;
//   sheet.getRangeByIndex(r, 1).setText('Findings by Category');
//   sheet.getRangeByIndex(r, 1).cellStyle.bold = true;
//   r++;
//   for (final e in categoryCounts.entries) {
//     sheet.getRangeByIndex(r, 1).setText(e.key);
//     sheet.getRangeByIndex(r, 2).setNumber(e.value.toDouble());
//     r++;
//   }

//   sheet.getRangeByIndex(r + 1, 1).setText('Top 10 Priority Fixes');
//   sheet.getRangeByIndex(r + 1, 1).cellStyle.bold = true;
//   final top = rows.where((e) => e[12].isNotEmpty).toList()
//     ..sort((a, b) => int.parse(a[12]).compareTo(int.parse(b[12])));
//   r += 2;
//   for (var i = 0; i < top.length && i < 10; i++) {
//     sheet.getRangeByIndex(r + i, 1).setText('${top[i][0]} — ${top[i][4]}');
//     sheet.getRangeByIndex(r + i, 2).setText(top[i][2]);
//   }

//   sheet.getRangeByIndex(1, 1, r + 10, 2).autoFitColumns();
// }

// List<List<String>> _findings() {
//   return [
//     _f(
//       'QA-001',
//       'Bug',
//       'Critical',
//       'Login',
//       'Silent login failure',
//       'Login only navigates when API response is non-null. Catch block only logs to console.',
//       '1. Enter credentials\n2. API returns null or throws non-Dio error',
//       'Clear error snackbar/dialog shown',
//       'Spinner stops; user stays on login with no message',
//       'Show showError() when response is null and in catch block',
//       r'lib\app\modules\Login\login_controller.dart',
//       'Open',
//       '2',
//     ),
//     _f(
//       'QA-002',
//       'Bug',
//       'High',
//       'Login',
//       'Weak password validation',
//       'Password validator allows minimum 3 characters.',
//       'Sign in with 3-character password',
//       'Stronger password policy (8+ chars)',
//       'Accepts 3-character passwords',
//       'Align validation with backend policy',
//       r'lib\app\modules\Login\login_controller.dart',
//       'Open',
//       '15',
//     ),
//     _f(
//       'QA-003',
//       'Bug',
//       'High',
//       'Login',
//       'Misleading validation messages',
//       'Validators show "email"/"password" errors for registration key / device label fields.',
//       'Submit login form with empty fields',
//       'Field-specific error labels',
//       'Confusing copied validation messages',
//       'Rename validators and error strings to match login fields',
//       r'lib\app\modules\Login\login_controller.dart',
//       'Open',
//       '20',
//     ),
//     _f(
//       'QA-004',
//       'Bug',
//       'Medium',
//       'Login',
//       'Login proceeds without outlet',
//       'App navigates to home even when outletData is null or empty.',
//       'Log in with account that has no outlets configured',
//       'Outlet setup prompt or error',
//       'Lands in app with no selected outlet',
//       'Block navigation and show setup flow when no outlets',
//       r'lib\app\modules\Login\login_controller.dart',
//       'Open',
//       '18',
//     ),
//     _f(
//       'QA-005',
//       'Bug',
//       'Medium',
//       'Login',
//       'Label mismatch: Request registration key',
//       'Button says "Request registration key" but opens Forgot Password flow.',
//       'Tap link on login screen',
//       'Label matches behavior',
//       'Mismatched label and action',
//       'Rename to "Forgot password?" or implement registration key flow',
//       r'lib\app\modules\Login\login_screen.dart',
//       'Open',
//       '25',
//     ),
//     _f(
//       'QA-006',
//       'Bug',
//       'Medium',
//       'Login',
//       'Stub Add Device shows fake success',
//       'onAddDevice() simulates delay and shows success without API call.',
//       'Submit add-device form if exposed',
//       'Real device registration via API',
//       'Fake success after 2s delay',
//       'Wire to real API or remove/hide feature',
//       r'lib\app\modules\Login\login_controller.dart',
//       'Open',
//       '30',
//     ),
//     _f(
//       'QA-007',
//       'Bug',
//       'Critical',
//       'Security',
//       'Global SSL certificate bypass',
//       'MyHttpOverrides accepts all TLS certificates; set globally in main and login.',
//       'MITM on public/corporate Wi-Fi',
//       'Valid certificate validation',
//       'All certificates trusted',
//       'Remove bypass in production; use proper certs or pinning',
//       r'lib\app\services\Network\api_overRides.dart; lib\main.dart; login_controller.dart',
//       'Open',
//       '1',
//     ),
//     _f(
//       'QA-008',
//       'Bug',
//       'High',
//       'Auth / Staff',
//       'Staff session flag never enforced',
//       'isStaffSession is set on login but never checked elsewhere for RBAC.',
//       'Log in as staff; access admin screens',
//       'Role-based route/action restrictions',
//       'No RBAC enforcement in UI',
//       'Gate routes and actions on isStaffSession and permissions',
//       r'lib\app\modules\Login\login_controller.dart; lib\config\app_pref.dart',
//       'Open',
//       '8',
//     ),
//     _f(
//       'QA-009',
//       'Improvement',
//       'Low',
//       'Splash',
//       'Fixed 3-second splash delay',
//       'Splash always waits 3 seconds before routing regardless of init speed.',
//       'Launch app',
//       'Navigate when initialization completes',
//       'Artificial 3s wait every launch',
//       'Route as soon as auth/prefs are ready',
//       r'lib\app\modules\splash\splash_controller.dart',
//       'Open',
//       '45',
//     ),
//     _f(
//       'QA-010',
//       'Bug',
//       'High',
//       'Add Order',
//       'Generic offline save failure message',
//       'Offline branch catch shows generic failed_to_save_order_offline without root cause.',
//       'Save order offline when DB write fails',
//       'Actionable error with reason',
//       'Generic offline failure message only',
//       'Log and surface specific failure reason',
//       r'lib\app\modules\AddOrder\add_order_controller.dart',
//       'Open',
//       '14',
//     ),
//     _f(
//       'QA-011',
//       'Improvement',
//       'Medium',
//       'Add Order / Sync',
//       'Offline orders do not trigger immediate sync',
//       'Offline save writes to DB but does not call SyncManager.triggerSync() when back online from this flow.',
//       'Create offline order; reconnect network',
//       'Prompt sync attempt on reconnect',
//       'Relies on 15-min timer or connectivity listener only',
//       'Trigger sync after successful offline save when online',
//       r'lib\app\modules\AddOrder\add_order_controller.dart; lib\app\services\sync\sync_manager.dart',
//       'Open',
//       '22',
//     ),
//     _f(
//       'QA-012',
//       'Bug',
//       'Medium',
//       'Add Order / Tables',
//       'Dine-in table conflict edge cases offline',
//       'Active table order check may desync across offline terminals.',
//       'Two terminals offline assign same table',
//       'Consistent conflict prevention',
//       'Depends on local state freshness',
//       'Strengthen offline table locking and conflict UI',
//       r'lib\app\modules\AddOrder\add_order_controller.dart',
//       'Open',
//       '28',
//     ),
//     _f(
//       'QA-013',
//       'Bug',
//       'Medium',
//       'KOT Preview',
//       'Null-force crash on staff/user',
//       'getUserDetails() uses appPref.user! and outletData!.first without null checks.',
//       'Open KOT preview with incomplete profile or staff session',
//       'Graceful fallback names',
//       'Possible runtime crash',
//       'Null-safe access with fallback values',
//       r'lib\app\modules\Invoice\KOT\kot_preview_controller.dart',
//       'Open',
//       '16',
//     ),
//     _f(
//       'QA-014',
//       'Bug',
//       'Medium',
//       'KOT Print',
//       'KOT PDF export unimplemented',
//       'buildPdf() throws UnimplementedError.',
//       'Trigger KOT PDF export path',
//       'Working PDF or disabled UI',
//       'Runtime UnimplementedError',
//       'Implement PDF generation or hide/disable action',
//       r'lib\app\services\printerService.dart\thermal_printer\kot_print.dart',
//       'Open',
//       '24',
//     ),
//     _f(
//       'QA-015',
//       'Improvement',
//       'Low',
//       'Add Order',
//       'Order preferences navigation commented out',
//       'Order preferences route call is commented out in controller.',
//       'Try accessing preferences from add-order flow',
//       'Working preferences shortcut',
//       'Dead code path',
//       'Restore navigation or remove UI entry',
//       r'lib\app\modules\AddOrder\add_order_controller.dart',
//       'Open',
//       '50',
//     ),
//     _f(
//       'QA-016',
//       'Bug',
//       'High',
//       'Item Reports',
//       'Null crash on payment filter',
//       'Offline filter uses order.paymentReceivedIn!.toLowerCase() — crashes when null.',
//       'Filter Item Reports by payment type with orders missing payment field',
//       'Null-safe filter match',
//       'Null assertion crash',
//       'Use ?.toLowerCase() ?? "" like order reports',
//       r'lib\app\modules\Reports\ItemReports\item_reports_controller.dart',
//       'Open',
//       '7',
//     ),
//     _f(
//       'QA-017',
//       'Improvement',
//       'Medium',
//       'Reports',
//       'Customer filter not implemented',
//       'filterByCustomers() shows coming soon; selectedCustomers filter state unused in UI.',
//       'Open reports and look for customer filter',
//       'Working customer filter dialog',
//       'Stub message; dead backend filter state',
//       'Implement dialog or remove filter UI/state',
//       r'lib\app\modules\Reports\ItemReports\item_reports_controller.dart; OrderReports\order_reports_controller.dart',
//       'Open',
//       '32',
//     ),
//     _f(
//       'QA-018',
//       'Bug',
//       'Medium',
//       'Business Overview',
//       'Wrong navigation to Item Reports',
//       'Uses Get.toNamed(AppRoute.itemReports) instead of Modular shell route.',
//       'From Business Overview empty state tap View Item Reports',
//       'Opens item reports inside shell',
//       'May push outside Modular context / wrong stack',
//       'Use Modular.to.pushNamed(HomeMainRoutes.itemsReport)',
//       r'lib\app\modules\Reports\BusinessOverview\business_overview_screen.dart',
//       'Open',
//       '26',
//     ),
//     _f(
//       'QA-019',
//       'Improvement',
//       'Low',
//       'Order Reports',
//       'PDF preview route commented out',
//       'Large block of invoice PDF preview navigation is commented.',
//       'Tap invoice action in order reports if visible',
//       'PDF preview opens',
//       'Incomplete or alternate path only',
//       'Finish PDF preview or remove dead code',
//       r'lib\app\modules\Reports\OrderReports\order_reports_screen.dart',
//       'Open',
//       '48',
//     ),
//     _f(
//       'QA-020',
//       'Bug',
//       'Medium',
//       'Order Reports',
//       'Hard null on user ID fetch',
//       'API call uses appPref.user!.id! without guard.',
//       'Open reports with cleared or corrupt user pref',
//       'Error message shown',
//       'Possible crash',
//       'Guard user/outlet before API calls',
//       r'lib\app\modules\Reports\OrderReports\order_reports_controller.dart',
//       'Open',
//       '21',
//     ),
//     _f(
//       'QA-021',
//       'Bug',
//       'High',
//       'Tables',
//       'Fake default tables on API failure',
//       'When API returns empty/fails, _defaultTables() generates 12 local phantom tables.',
//       'Open Tables with API down or new outlet',
//       'Empty state or error message',
//       '12 invented tables shown (table_1..table_12)',
//       'Show error/empty state; do not invent tables',
//       r'lib\app\modules\Tables\table_controller.dart',
//       'Open',
//       '6',
//     ),
//     _f(
//       'QA-022',
//       'Bug',
//       'High',
//       'Tables',
//       'Table free-after-payment incomplete',
//       'closeOrderAndFreeTable() DB update is commented out; only calls loadTables().',
//       'Complete payment and free table',
//       'Order closed in DB and table available',
//       'Table may remain occupied until reload/sync',
//       'Restore DB update logic',
//       r'lib\app\modules\Tables\table_controller.dart',
//       'Open',
//       '9',
//     ),
//     _f(
//       'QA-023',
//       'Bug',
//       'High',
//       'Kitchen Display',
//       'Windows defaults to localhost WebSocket',
//       'On Windows KDS WS defaults to ws://127.0.0.1:3000 while REST may use remote tunnel URL.',
//       'Run KDS on Windows without .env KDS flags against remote backend',
//       'WebSocket host matches REST API',
//       'WS connects to localhost by default',
//       'Default _useLocalKdsWebSocket to false for production builds',
//       r'lib\app\services\Network\api_config.dart',
//       'Open',
//       '11',
//     ),
//     _f(
//       'QA-024',
//       'Bug',
//       'Medium',
//       'Kitchen Display',
//       'KDS disconnect errors swallowed',
//       'WebSocket close errors caught with empty catch blocks.',
//       'Disconnect during network flap',
//       'Surfaced error/reconnect status',
//       'Silent failure',
//       'Log/show lastError; avoid empty catches',
//       r'lib\app\services\kds\kds_realtime_service.dart',
//       'Open',
//       '33',
//     ),
//     _f(
//       'QA-025',
//       'Bug',
//       'Medium',
//       'KOT History',
//       'Load errors hidden from user',
//       'load() / loadMore() catch blocks only debugPrint.',
//       'Corrupt DB or load failure in KOT History',
//       'User-visible error with retry',
//       'Silent empty list',
//       'Show error banner and retry button',
//       r'lib\app\modules\KOTHistory\kot_history_controller.dart',
//       'Open',
//       '27',
//     ),
//     _f(
//       'QA-026',
//       'Improvement',
//       'Low',
//       'Routes',
//       'Typo in WhatsApp route constant',
//       'Route named whatsaapMarketing (misspelled).',
//       'Inspect route names / deep links',
//       'Consistent whatsappMarketing naming',
//       'Typo persisted in route ID',
//       'Rename with migration plan',
//       r'lib\app\modules\HomeMain\home_main_routes.dart',
//       'Open',
//       '52',
//     ),
//     _f(
//       'QA-027',
//       'Bug',
//       'Medium',
//       'Printer',
//       'Bluetooth not supported error on desktop',
//       'checkBluetoothPermission() shows error if FlutterBluePlus.isSupported is false.',
//       'Open Printer screen on Windows without BT stack',
//       'USB-first UX on Windows',
//       'Error snackbar even if USB printing works',
//       'Gate BT messaging by platform; default to USB tab on Windows',
//       r'lib\app\modules\Printer\printer_controller.dart',
//       'Open',
//       '29',
//     ),
//     _f(
//       'QA-028',
//       'Bug',
//       'Medium',
//       'Printer',
//       'Empty catch blocks hide print failures',
//       'Multiple printer helpers swallow exceptions silently.',
//       'Print or connect failure',
//       'User notified of failure',
//       'Silent failure possible',
//       'Surface errors to UI snackbar/dialog',
//       r'lib\app\services\printerService.dart\thermal_printer\thermal_printer_service.dart',
//       'Open',
//       '31',
//     ),
//     _f(
//       'QA-029',
//       'Bug',
//       'Medium',
//       'KOT Print',
//       'KOT validation requires waiter name',
//       'KotPrintJob.validate() fails if waiterName is empty.',
//       'Auto-print KOT when brandName/waiter missing',
//       'Print with fallback staff name',
//       'Validation failure prevents print',
//       'Relax validation or always set fallback name',
//       r'lib\app\services\printerService.dart\thermal_printer\kot_print.dart',
//       'Open',
//       '34',
//     ),
//     _f(
//       'QA-030',
//       'Bug',
//       'High',
//       'Customers',
//       'Empty list shows onboarding not list',
//       'customerList.isEmpty renders CustomerTrackingScreen for loading, API failure, and zero customers.',
//       'Open Customers before API returns or after API error',
//       'Loader then list or proper empty state',
//       'Onboarding/marketing screen shown incorrectly',
//       'Add loading/error states; distinguish zero customers',
//       r'lib\app\modules\Regular customer\CustomerList\customer_list_Screen.dart',
//       'Open',
//       '5',
//     ),
//     _f(
//       'QA-031',
//       'Bug',
//       'High',
//       'Customers',
//       'Force-unwrap on failed API',
//       'Uses response!.status when callApi returns null.',
//       'Open customers offline or on API error',
//       'Error message shown',
//       'Null check operator crash',
//       'Use response?.status and error UI',
//       r'lib\app\modules\Regular customer\CustomerList\cutomer_list_controller.dart',
//       'Open',
//       '4',
//     ),
//     _f(
//       'QA-032',
//       'Improvement',
//       'Medium',
//       'Customers',
//       'Typo in controller class name',
//       'CutomerListController misspelled throughout module.',
//       'N/A (maintainability)',
//       'CustomerListController naming',
//       'Typo in type and file name',
//       'Rename class and file for maintainability',
//       r'lib\app\modules\Regular customer\CustomerList\cutomer_list_controller.dart',
//       'Open',
//       '46',
//     ),
//     _f(
//       'QA-033',
//       'Bug',
//       'High',
//       'Staff',
//       'Wrong permission mapping for Edit menu',
//       'UI flag canEditMenuItems maps to permission view_reports not menu edit.',
//       'Create biller with Edit menu checked',
//       'Menu edit permission granted',
//       'Only view_reports granted',
//       'Map to correct backend permission key',
//       r'lib\app\modules\Staff\add_staff_controller.dart',
//       'Open',
//       '10',
//     ),
//     _f(
//       'QA-034',
//       'Bug',
//       'Medium',
//       'Staff',
//       'Hydration maps wrong permission to UI',
//       'When editing staff, canEditMenuItems set from view_reports permission.',
//       'Edit existing staff member',
//       'Checkbox reflects menu edit permissions',
//       'Mislabeled capability in UI',
//       'Fix permission to UI mapping both directions',
//       r'lib\app\modules\Staff\add_staff_controller.dart',
//       'Open',
//       '23',
//     ),
//     _f(
//       'QA-035',
//       'Improvement',
//       'Low',
//       'Signup',
//       'Address save not persisted to backend',
//       'AddAddressController.saveAddress() has TODO; only print and local result.',
//       'Complete signup address step',
//       'Address saved via API',
//       'Local-only save',
//       'Implement API persistence',
//       r'lib\app\modules\Signup\address_controller.dart',
//       'Open',
//       '49',
//     ),
//     _f(
//       'QA-036',
//       'Bug',
//       'Critical',
//       'WhatsApp Marketing',
//       'Hardcoded dev ngrok URL and phone numbers',
//       'Bulk send posts to ngrok URL with hardcoded Indian test numbers.',
//       'Send WhatsApp campaign from app',
//       'Outlet customer list and production API',
//       'Dev tunnel and fixed test numbers used',
//       'Load customers from DB/API; configurable endpoint',
//       r'lib\app\modules\Whatsapp Marketing\whatsapp_marketing_controller.dart',
//       'Open',
//       '3',
//     ),
//     _f(
//       'QA-037',
//       'Improvement',
//       'Medium',
//       'WhatsApp Marketing',
//       'Primary bulk-send flow commented out',
//       'sendBulkWhatsAppMessages and validation fully commented; ngrok path is active workaround.',
//       'Use non-ngrok template send',
//       'Production WhatsApp integration',
//       'Dead code; ngrok workaround only',
//       'Restore/implement official Twilio integration',
//       r'lib\app\modules\Whatsapp Marketing\whatsapp_marketing_controller.dart',
//       'Open',
//       '35',
//     ),
//     _f(
//       'QA-038',
//       'Improvement',
//       'Low',
//       'Settings / Menu',
//       'Language change menu disabled',
//       'Language menu item commented out in Menu screen.',
//       'Menu → Language',
//       'Language settings accessible',
//       'Entry removed/commented',
//       'Re-enable HomeMainRoutes.changeLanguage',
//       r'lib\app\modules\Menu\menu_screen.dart',
//       'Open',
//       '47',
//     ),
//     _f(
//       'QA-039',
//       'Improvement',
//       'Low',
//       'Branding',
//       'Inconsistent product naming in UI',
//       'Window title Billkaro ChillKaro, app title BillKaro, exit dialog double space.',
//       'View title bar and exit dialog',
//       'Consistent brand string',
//       'Mixed spelling and spacing',
//       'Standardize branding copy across app',
//       r'lib\main.dart; lib\app\Widgets\windows_desktop_title_bar.dart; lib\utils\exit_confirm_helper.dart',
//       'Open',
//       '51',
//     ),
//     _f(
//       'QA-040',
//       'Improvement',
//       'Low',
//       'Module naming',
//       'OrderPrefrences typo in folder/module',
//       'Folder and imports use OrderPrefrences / order_prefrences_*.',
//       'N/A (maintainability)',
//       'OrderPreferences naming',
//       'Typo persisted in paths',
//       'Rename module in refactor',
//       r'lib\app\modules\OrderPrefrences\',
//       'Open',
//       '53',
//     ),
//     _f(
//       'QA-041',
//       'Bug',
//       'High',
//       'Offline Sync',
//       'Only selected outlet pending orders sync',
//       'syncPendingOrders filters pending orders to selectedOutletId only.',
//       'Save offline orders for outlet A; switch to outlet B; reconnect',
//       'All outlets sync or warning shown',
//       'Outlet A orders remain pending silently',
//       'Sync all pending orders or show cross-outlet pending count',
//       r'lib\app\services\Synchronisatioin\synchronisation.dart',
//       'Open',
//       '12',
//     ),
//     _f(
//       'QA-042',
//       'Bug',
//       'Medium',
//       'Offline Sync',
//       'No Windows sync notifications',
//       'SyncNotificationService initializes Android/iOS local notifications only.',
//       'Sync pending orders on Windows',
//       'In-app sync status indicator',
//       'Debug logs only',
//       'Add in-app toast/banner on Windows desktop',
//       r'lib\app\services\sync\sync_notification_service.dart; sync_manager.dart',
//       'Open',
//       '36',
//     ),
//     _f(
//       'QA-043',
//       'Bug',
//       'High',
//       'Offline Sync',
//       '4xx failed orders never retried, no user queue',
//       'Client errors logged as will not retry; orders stay pending with no surfaced queue UI.',
//       'Sync order rejected by server validation (4xx)',
//       'User notified with fix/retry flow',
//       'Stuck pending in DB silently',
//       'Surface failed sync list; allow edit/delete/retry',
//       r'lib\app\services\Synchronisatioin\synchronisation.dart',
//       'Open',
//       '13',
//     ),
//     _f(
//       'QA-044',
//       'Bug',
//       'High',
//       'Network / Auth',
//       '502 response triggers logout',
//       'On 502 interceptor calls _handleTokenExpiration() clearing all data.',
//       'Server returns 502 during normal use',
//       'Retry message; stay logged in',
//       'Session cleared / forced logout',
//       'Treat 502 as transient; do not clear session',
//       r'lib\app\services\Network\network_module.dart',
//       'Open',
//       '5',
//     ),
//     _f(
//       'QA-045',
//       'Bug',
//       'Critical',
//       'Config',
//       'Default API points to dev tunnel',
//       'Fallback base URL is devtunnels.ms when .env missing.',
//       'Run production build without .env',
//       'Production API endpoint',
//       'Dev tunnel endpoint used',
//       'Require env/config for release; fail fast if unset',
//       r'lib\app\services\Network\urls.dart; api_config.dart',
//       'Open',
//       '1',
//     ),
//     _f(
//       'QA-046',
//       'Test Gap',
//       'Critical',
//       'Tests',
//       'Only broken default widget test',
//       'Single test expects counter app and imports billkaro_windows/main.dart while package is billkaro.',
//       'Run flutter test in billkaro_windows',
//       'Passing suite covering core flows',
//       '0/1 tests pass — compile failure',
//       'Replace with real tests; fix import to package:billkaro/main.dart',
//       r'billkaro_windows\test\widget_test.dart',
//       'Open',
//       '1',
//     ),
//     _f(
//       'QA-047',
//       'Test Gap',
//       'High',
//       'Tests',
//       'No auth flow tests',
//       'No unit/widget tests for login, staff login, token expiry, splash routing.',
//       'Run flutter test',
//       'Login success/failure/session tests',
//       'Zero coverage',
//       'Add controller tests with mocked ApiClient',
//       r'billkaro_windows\test\',
//       'Open',
//       '17',
//     ),
//     _f(
//       'QA-048',
//       'Test Gap',
//       'High',
//       'Tests',
//       'No order/offline sync tests',
//       'No tests for offline order save, pending sync, 4xx handling, outlet filtering.',
//       'Run flutter test',
//       'Sync integration tests',
//       'None exist',
//       'Add tests with in-memory DB and mock API',
//       r'synchronisation.dart; add_order_controller.dart',
//       'Open',
//       '19',
//     ),
//     _f(
//       'QA-049',
//       'Test Gap',
//       'Medium',
//       'Tests',
//       'No reports export/filter tests',
//       'Excel/PDF export and payment/date filters untested.',
//       'Run flutter test',
//       'Filter/export regression tests',
//       'None exist',
//       'Test applyAllFilters() and export helpers',
//       r'item_reports_controller.dart; order_reports_controller.dart',
//       'Open',
//       '37',
//     ),
//     _f(
//       'QA-050',
//       'Test Gap',
//       'Medium',
//       'Tests',
//       'No printer/KDS integration tests',
//       'Printer assignment, KOT validation, KDS WS reconnect logic untested.',
//       'Run flutter test',
//       'Unit tests for critical paths',
//       'None exist',
//       'Add mocked printer/KDS service tests',
//       r'printer_controller.dart; kds_realtime_service.dart',
//       'Open',
//       '38',
//     ),
//     _f(
//       'QA-051',
//       'Bug',
//       'High',
//       'Network',
//       'Connectivity check type mismatch',
//       'NetworkUtils.hasInternetConnection compares List<ConnectivityResult> to ConnectivityResult.none (unrelated types).',
//       'Call hasInternetConnection() on device',
//       'Correct none-network detection',
//       'Connectivity none check may never match; wrong online/offline state',
//       'Use result.contains(ConnectivityResult.none) like ConnectivityHelper',
//       r'lib\utils\connectivity\connectivity_helper.dart',
//       'Open',
//       '3',
//     ),
//     _f(
//       'QA-052',
//       'Test Gap',
//       'High',
//       'billkaro-app',
//       'Missing app_snackbar.dart breaks 4 tests',
//       'billkaro-app imports utils/app_snackbar.dart which does not exist in that project.',
//       'Run flutter test in billkaro-app',
//       'All tests compile and pass',
//       '14/18 pass; 4 fail to compile',
//       'Copy app_snackbar.dart from billkaro_windows or fix import',
//       r'billkaro-app\lib\app\services\notification\kitchen_new_order_notification_service.dart',
//       'Open',
//       '4',
//     ),
//     _f(
//       'QA-053',
//       'Improvement',
//       'Medium',
//       'Code Quality',
//       '1441 static analysis issues',
//       'Mostly deprecated withOpacity, unnecessary imports, avoid_print; indicates tech debt.',
//       'Run flutter analyze',
//       'Minimal warnings in CI',
//       '1441 info/warning issues; 2 errors in test file',
//       'Enable CI analyze gate; fix critical warnings incrementally',
//       r'billkaro_windows\lib\',
//       'Open',
//       '39',
//     ),
//     _f(
//       'QA-054',
//       'Improvement',
//       'Medium',
//       'Dependencies',
//       '107 packages have newer incompatible versions',
//       'Run flutter pub outdated',
//       'Up-to-date secure dependencies',
//       'Many packages behind latest',
//       'Plan dependency upgrade sprint with regression testing',
//       r'billkaro_windows\pubspec.yaml',
//       'Open',
//       '40',

//     ),
//     _f(
//       'QA-055',
//       'Improvement',
//       'Low',
//       'Build',
//       'CMake/NuGet warnings during Windows build',
//       'Nuget not installed warning; webview_windows CMP0175 policy warning during build.',
//       'flutter build windows',
//       'Clean build without warnings',
//       'Build succeeds but with developer warnings (392.8s)',
//       'Install NuGet; update webview_windows CMake policy',
//       r'build\windows\',
//       'Open',
//       '54',
//     ),
//     _f(
//       'QA-056',
//       'Improvement',
//       'Medium',
//       'Home / Dashboard',
//       'Large home_screen.dart file (1600+ lines)',
//       'Monolithic UI file increases bug risk and slows maintenance.',
//       'Navigate home dashboard',
//       'Modular widget composition',
//       'Single large file hard to test and maintain',
//       'Extract chart, stats, and order list into separate widgets',
//       r'lib\app\modules\Home\home_screen.dart',
//       'Open',
//       '41',
//     ),
//     _f(
//       'QA-057',
//       'Improvement',
//       'Medium',
//       'Add Order',
//       'add_order_controller.dart is 2600+ lines',
//       'God controller mixing UI state, API, sync, KOT, and table logic.',
//       'Create/edit order flow',
//       'Separated concerns (service layers)',
//       'Hard to test; high regression risk',
//       'Split into OrderCreationService, BillNumberService, KotPrintCoordinator',
//       r'lib\app\modules\AddOrder\add_order_controller.dart',
//       'Open',
//       '42',
//     ),
//     _f(
//       'QA-058',
//       'Bug',
//       'Medium',
//       'Keyboard (Windows)',
//       'Hardware keyboard state workaround needed',
//       'App requires dynamic clearState() workaround for Alt-key stuck after native dialogs.',
//       'Open file dialog then press Alt',
//       'Normal keyboard state after dialog',
//       'Framework assertion without workaround',
//       'Track Flutter desktop fix; keep workaround documented',
//       r'lib\main.dart',
//       'Open',
//       '43',
//     ),
//     _f(
//       'QA-059',
//       'Improvement',
//       'Low',
//       'Workmanager',
//       'Background sync not available on Windows',
//       'Workmanager skipped on Windows; sync relies on in-app connectivity listener.',
//       'Close app with pending offline orders on Windows',
//       'Background sync when app closed',
//       'Sync only when app is running',
//       'Document limitation; consider Windows background task alternative',
//       r'lib\main.dart; lib\app\services\sync\sync_manager.dart',
//       'Open',
//       '44',
//     ),
//     _f(
//       'QA-060',
//       'Improvement',
//       'Medium',
//       'Customer UX',
//       'Limited automated E2E customer journey tests',
//       'No integration test simulating login → create order → payment → report export on Windows.',
//       'Manual full customer journey',
//       'Automated E2E on CI',
//       'Manual testing only',
//       'Add integration_test package with mocked API',
//       r'billkaro_windows\test\',
//       'Open',
//       '55',
//     ),
//   ];
// }

// List<String> _f(
//   String id,
//   String category,
//   String severity,
//   String module,
//   String title,
//   String description,
//   String steps,
//   String expected,
//   String actual,
//   String fix,
//   String paths,
//   String status,
//   String priority,
// ) {
//   return [
//     id,
//     category,
//     severity,
//     module,
//     title,
//     description,
//     steps,
//     expected,
//     actual,
//     fix,
//     paths,
//     status,
//     priority,
//   ];
// }
